version: "3.7"
services:
  flask_app:
    build: './question_generator_app'
    environment:
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
    ports:
      - "5000:5000"
    depends_on:
      - redis

  simple_worker:
    build: './main_worker'
    user: root
    volumes:
      - /Users/erdemisbilen/Code:/data
    depends_on:
      - redis
      - flask_app

  redis:
    image: 'redis:4-alpine'
    ports:
      - '6379:6379'

  flower:  
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=8888
    ports:  
      - 8888:8888
